version: '3.3'

services:
  proxy:
    image: nginx:stable-alpine
    container_name: simplecrypto-proxy
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./letsencrypt:/data/letsencrypt/
      - ./nginx-h5bp/server-configs-nginx-master:/etc/nginx/
      - /home/manager/nginx-logs:/var/log/nginx/
      - /etc/letsencrypt:/etc/letsencrypt/
  mysql:
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:latest
    container_name: simplecrypto-mysql
    hostname: simplecrypto-mysql
    volumes:
      - /home/manager/simplecrypto-mysql:/data/db
    env_file:
      - .env
    ports:
      - '3306'
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
  server:
    image: simplecrypto/server
    container_name: simplecrypto-server
    hostname: simplecrypto-server
    restart: always
    build:
      context: ./simplecrypto-backend
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - /home/manager/simplecrypto-upload:/usr/src/app/public/upload
  client:
    image: simplecrypto/client
    container_name: simplecrypto-client
    hostname: simplecrypto-client
    restart: always
    env_file:
      - .env
    build:
      context: ./simplecrypto-frontend
